### ISSUE TITLE
TypeError: (Handlebars.default || Handlebars).template is not a function

### ISSUE THREAD

**Issue by larryhe** [tylergould/handlebars-jest#2]
I am migrating our legacy unit tests (jquery+handlebars+jasmine+karma) to Jest, following the instruction here. but got `TypeError: (Handlebars.default || Handlebars).template is not a function` any ideas? are you able to run test correctly?

**Comment by scitech** [comment]
Yep, this works for me on basic projects using Handlebars 3/4. Can you share any other information about your project, or the relevant parts of your Jest config? Are you using `require` or `import`?

**Comment by larryhe** [comment]
@tylergould  thanks for you reply. seems that it's my jest config issue and after simplifying it a little bit, the issue is gone. but found handlebars-jest could not handle partials.

**Comment by scitech** [comment]
True, as of yet it is very basic. I'll add partials tomorrow 👍

**Comment by scitech** [comment]
@larryhe, can you try 0.2.0? Partials should work now.

**Comment by larryhe** [comment]
Hi @tylergould just tried on our code base with thousands of handlebar template. It worked like a charm. Thanks sooo much for your quick response. big 👍
