### ISSUE TITLE
Breaking change in jest v27 changes how config is passed to process()

### ISSUE THREAD

**Issue by clang13** [tylergould/handlebars-jest#26]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `handlebars-jest@0.6.0` for the project I'm working on.

https://github.com/facebook/jest/pull/10834 (in jest v27.0.0) made a breaking change to the Transformer.process function signature, where the project config is now nested inside an options parameter rather than passed directly. This was breaking reading of the config.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/handlebars-jest/lib/process.js b/node_modules/handlebars-jest/lib/process.js
index 8176415..c673733 100644
--- a/node_modules/handlebars-jest/lib/process.js
+++ b/node_modules/handlebars-jest/lib/process.js
@@ -16,7 +16,7 @@ function precompileTemplate(src, config) {
 /**
  * Transforms a handlebars template source file into a precompiled template function.
  */
-module.exports = function(src, filename, config) {
+module.exports = function(src, filename, { config }) {
   const handlebarsJestConfig = getHandlebarsJestConfig(config);
   const template = precompileTemplate(src, handlebarsJestConfig);
   const runtimePath = require.resolve('handlebars/runtime');
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by scitech** [comment]
Thank you for filing the issue. This should be fixed by #29
